import os

VERSION = 0.1

DATABASE_NAME = os.getenv("MONGODB_DATABASE", "referral")
DATABASE_HOST = os.getenv("MONGODB_HOST", "localhost")
DATABASE_PORT = os.getenv("MONGODB_PORT", 27017)
DATABASE_USER = os.getenv("MONGODB_USER", "")
DATABASE_PASSWORD = os.getenv("MONGODB_PASSWORD", "")

ENDPOINT_CALLBACK_CREDIT_ON_SIGNUP = os.getenv("ENDPOINT_BILLING_CREDIT","")